var htmlAnchor = $('<a target="_blank">');
var htmlBody = $('body');
var htmlBreak = $('<br/>');
var htmlButton = $('<button></button>');
var htmlDiv = $('<div></div>');
var htmlFooter = $('<footer></footer>');
var htmlHeader = $('<header></header>');
var htmlInputFile = $('<input type="file" name="files[]" multiple />');
var htmlInputText = $('<input type="text" />');
var htmlParagraph = $('<p></p>');
var htmlSection = $('<section></section>');
var htmlSpan = $('<span></span>');